### ISSUE TITLE
Общее

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/light-range-slider#1]
- Надо бы добавить в readme обоих проектов npm команды и их описание, которые используются в проекте (npm run start/build/etc.). 
- В зависимостях нет cross-env, я не могу запустить скрипты.
- Демо страница слайдера тоже должна быть на gh-pages и ссылка на неё в readme.
- Что за файл testing.webpack.js?
- Похоже, что consolidating-observer.ts нигде не используется. Нужно избавиться от старого и неиспользуемого кода, это сильно ускорит ревью.

**Comment by Rizarid** [comment]
> * Что за файл testing.webpack.js?

Это настройки webpack для тестовых файлов. Он импортируется в karma.conf.js
