### ISSUE TITLE
Баги и работа плагина

### ISSUE THREAD

**Issue by FanManutd** [Rizarid/light-range-slider#2]
Ползунок следует за курсором с ощутимой задержкой. И судя по инпуту `From`, значения меняются действительно как-то.. не линейно, перескакивают. 
![задержка](https://user-images.githubusercontent.com/90761929/136563717-32fcfebb-1365-482e-b611-3b43ac768487.gif)

Если резко дёргнуть в одну сторону и остановиться, ползунок останавливается не доходя до курсора. И доходит до курсора только после следующего движения мышкой. 
![дёргнул](https://user-images.githubusercontent.com/90761929/136564064-ded8e973-3bf6-4888-985b-0baf7c400baf.gif)

Плагин не перестраивается при изменении размеров окна.
![отзывчивость](https://user-images.githubusercontent.com/90761929/136564897-37fea98f-bc1e-4f83-8c7b-e6e27e39455a.gif)

Скопировал коллекцию из примера ниже в 1й пример, не работает. 
![image](https://user-images.githubusercontent.com/90761929/136565555-7c7b17f6-113d-4b3f-b035-998094b109a9.png)

Если предустановить значение в `to`, а зачем включить двойной слайдер, то `to`сбросится в максимальное значение.
![to](https://user-images.githubusercontent.com/90761929/136565937-b7c497c7-1b1c-4646-b0c7-08107d0260b3.gif)

баг
![баг](https://user-images.githubusercontent.com/90761929/136566383-bd43fc27-7f76-4368-87bf-a6148f1cc91a.gif)

После применения некоторых неправильных значений, выскакивает ошибка и значение не применяется, но значение в инпуте остаётся неизменным. И меняется на корректное только при взаимодействии со слайдером. 
![1](https://user-images.githubusercontent.com/90761929/136567750-2ebca4a3-57b1-4330-9261-df9ec53be8cd.gif)

**Comment by Rizarid** [comment]
> Если резко дёргнуть в одну сторону и остановиться, ползунок останавливается не доходя до курсора. И доходит до курсора только после следующего движения мышкой.

Для повышения производительности я сделал ограничение на частоту опроса события:
![image](https://user-images.githubusercontent.com/60002712/136580519-6b90ec0e-9db6-424e-9df3-d53f118f91d6.png)
И если курсор останавливается во время блокирования опроса то получается такой эффект. В данном случае максимальная частота выставлена 100 миллисекунд что уменьшает нагрузку на вычислительные мощности раз в 100)
И тут вопрос настолько ли это критичный эффект, чтобы увеличивать нагрузку на вычислительные мощности в 100 раз.

**Comment by Rizarid** [comment]
> Ползунок следует за курсором с ощутимой задержкой. И судя по инпуту `From`, значения меняются действительно как-то.. не линейно, перескакивают.

При отключении transition ползунок дергается из-за задержки описанной выше. И изменение текущего значения происходит рывками по той же причине. Возможно это значение нужно вынести в параметры, чтобы пользователь сам решил что ему нужнее?
