### ISSUE TITLE
Общие правки

### ISSUE THREAD

**Issue by essserrr** [Rizarid/light-range-slider#6]
1. В Readme проекта следует указывать версии плагинов, на которых его писали.
2. В tsconfig должен быть установлен флаг strict: true. Так же следует помнить, что запрящается  добавлять в tsconfig флаги, ослабляющие проверки типов (например,  suppressImplicitAnyIndexErrors, suppressExcessPropertyErrors и т. п.). Так что следует выставить это флаг и проверить проект на наличие ошибок.
3. Отключать правила проверки запрещено. Стоит решить саму проблему, а не отключать правила для нее поиска. Примеры отключения:
![image](https://user-images.githubusercontent.com/21965602/142373019-58965625-3ba7-4838-b74c-2292b86be0a9.png)
![image](https://user-images.githubusercontent.com/21965602/142373026-a1b9d996-845b-4c12-b97c-c7702366981e.png)
4. У меня что-то куча ошибок в консоли при тестировании, например: 
![image](https://user-images.githubusercontent.com/21965602/142373093-b6b09df9-4b9b-490f-b80c-a4a53fd798fd.png)
При этом само тестирование завершается без ошибок.
5. В проекте следует вычислять покрытие тестами.

**Comment by Rizarid** [comment]
> 4\. У меня что-то куча ошибок в консоли при тестировании, например:
>     ![image](https://user-images.githubusercontent.com/21965602/142373093-b6b09df9-4b9b-490f-b80c-a4a53fd798fd.png)
>     При этом само тестирование завершается без ошибок.

Эти ошибки возникают при тестировании класса ValueChecker. Он проверяет записывающиеся в модель данные на корректность. При тестировании в него подаются заведомо не корректные данные, и он выбрасывает ошибки. Так как тесты и ожидают получить в данном месте ошибку, тесты завершаются успешно.

**Comment by Rizarid** [comment]
> 5\. В проекте следует вычислять покрытие тестами.

Покрытие тестами находится в папке tmp
![image](https://user-images.githubusercontent.com/60002712/142479182-1862df93-9b89-4a5f-9cba-9fbfd7ff1f4f.png)

**Comment by essserrr** [comment]
> > 5. В проекте следует вычислять покрытие тестами.
> 
> Покрытие тестами находится в папке tmp ![image](https://user-images.githubusercontent.com/60002712/142479182-1862df93-9b89-4a5f-9cba-9fbfd7ff1f4f.png)

Ага, понимаю. Мы обычно не тестируем варианты, которые заведомо противоречат здравому смыслу, например, вариант когда вместо числа пользователь передает в качестве аргумента строку. Мы тестируем случаи когда пользователь передает строку а программа может в на допустимый инпут повести себя как-то по-особенному,  например выдать неверный ответ.
