### ISSUE TITLE
Слайдер

### ISSUE THREAD

**Issue by essserrr** [Rizarid/light-range-slider#8]
1. Если количество айтемов в коллекции меньше 2, то в консоле появляется ошибка, а слайдер переходит в очень интересное состояние:
![image](https://user-images.githubusercontent.com/21965602/142377103-1d74a4aa-6923-4bbe-9529-4d46d9fc3190.png)

![image](https://user-images.githubusercontent.com/21965602/142377086-d0fba353-39a6-4a43-b8bc-f4e7caea45da.png)

Хотя на сколько я понимаю, по задумке просто должны появиться 0 и 1, а режим коллекции отключиться.
2. Если установить максимальное значение больше, чем длина коллекции, то слайдер перейдет в ошибочное состояние:
![image](https://user-images.githubusercontent.com/21965602/142377168-3e5d2084-7a6b-479b-aa0c-91c59f891676.png)
3. Шкале и шагу необходимо быть синхронизированными: если есть отметка на шкале, то в нее должно быть возможно попасть. При таких настройках, попасть в отметку **56** не представляется возможным:
![image](https://user-images.githubusercontent.com/21965602/142377249-22a106d3-c882-46a5-8682-701ac4e4c79d.png)
4. Вот еще пример. 
Максимальное значение 100.9. На шкале 101, на лейбле 100.9 при чем значение 100 и 101 слепляются.
![image](https://user-images.githubusercontent.com/21965602/142377290-1db247a6-aedc-40b7-8d80-9b1919ce3ecb.png)
Тут нужно решить что делать если пользователь все-таки передал неполный шаг, т.е. нужно что бы лейбл и шкала показывали хотя бы одинаковое значение. 
Слепливание по краям можно, например, исправить разделив визуально концы интервала от шкалы.
5. Слепливание отметок на шкале между собой это прямо проблема:
![image](https://user-images.githubusercontent.com/21965602/142377325-8eda410c-0810-45da-b33a-c009ec2a339a.png)
Если отметки не вмещаются, то слайдер должен показывать некоторое минимальное число отметок, которые точно вместятся при данной длине, а не превращать шкалу в месиво.
6. Значение не вмещаются в лейбл
![image](https://user-images.githubusercontent.com/21965602/142377369-fbd08803-c3b8-406b-ac20-493faa83b0e7.png)
7. Кстати слайдер переходит в режим с целыми если шаг слишком мал. Не знаю задумывалось это так или нет.
![image](https://user-images.githubusercontent.com/21965602/142377392-ae5d0b58-3104-4536-8684-d80b098fee92.png)

**Comment by Rizarid** [comment]
> 3. Шкале и шагу необходимо быть синхронизированными: если есть отметка на шкале, то в нее должно быть возможно попасть. При таких настройках, попасть в отметку **56** не представляется возможным:

> 5. Слепливание отметок на шкале между собой это прямо проблема:
> ![image](https://user-images.githubusercontent.com/21965602/142377325-8eda410c-0810-45da-b33a-c009ec2a339a.png)
> Если отметки не вмещаются, то слайдер должен показывать некоторое минимальное число отметок, которые точно вместятся при данной длине, а не превращать шкалу в месиво.

Когда я делал данный слайдер, я исходил из того, что пользователем плагина является другой разработчик, а не обычный пользователь сайта. Следовательно приоритетом является дать пользователю возможность наиболее гибко настраивать слайдер под его нужды, а не сидеть и пытаться просчитать все возможные способы, как пользователь может сломать верстку. Мне кажется что другой разработчик, сам способен определить нужна ли ему синхронизация размера шагов слайдера и шкалы, или какой размер шага шкалы ему нужно установить чтобы при его данных ничего друг на друга не наезжало. А возможность настроить это моя библиотека предоставляет.

**Comment by Rizarid** [comment]
> 7. Кстати слайдер переходит в режим с целыми если шаг слишком мал. Не знаю задумывалось это так или нет.

Это ограничения при преобразовании типов, которое производится при извлечении нового значения из инпута.
![image](https://user-images.githubusercontent.com/60002712/143311706-2c3264c9-b449-40e1-8493-228962614c28.png)

**Comment by essserrr** [comment]
1 - 6 все еще работают по-старому.

На счет №7.
Пользователь установил требуемый ему шаг, сладйер вместо этого шага установил другой шаг, а данные пользователя отбросил. Мне кажется, что это не ожидаемое поведение. Такие вещи стоило бы отдельно где-то указывать или сделать поддержку любого шага.
